### ISSUE TITLE
XmlDocMarkdown.Core.XmlDocMarkdownGenerator.Generate is holding on to files

### ISSUE THREAD

**Issue by brianhill-bfs** [ejball/XmlDocMarkdown#41]
I implemented a custom MS Build Task (Microsoft.Build.Utilities.Task) to automatically generate documents for all .xml files in a build output. It works fine the first run, but the default MSBuild reuse behavior is causing locks to any assembly loaded by the Generate method because it uses the Assembly.Load method. To prevent this, you have to read the assembly as a byte array and pass it to a new AppDomain.

```
AppDomain ad = AppDomain.CreateDomain("MyNewDomain");
byte[] assemblyBytes = File.ReadAllBytes("<path to assembly>");
var assembly = ad.Load(assemblyBytes); 
 ```

EDIT:
Well, crud.  AppDomains are not supported in .NET Standard (and won't be). So now to figure out an alternative...

**Comment by sungam3r** [comment]
Copy assembly is an alternative.

**Comment by ejball** [comment]
I would love to find a way to reflect over an assembly without loading it, but I'm not sure the best way to do that in .NET Core, and it would probably be a major rewrite that I don't currently have time for.

If possible, I'd recommend running the executable from the task instead of referencing the library.

It might be even simpler to use `<Exec>` from an MSBuild `<Target>`. I did something similar recently (a NuGet package that automatically adds a post-build target) and it was considerably easier than using `Microsoft.Build.Utilities.Task`.

**Comment by brianhill-bfs** [comment]
Yeah, that's the route I think I'll go with, the tool/target. Do you plan on publishing your version?

Looks like .NET Core 3.0 introduced [`AssemblyLoadContext.Unload`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.unload?view=netcore-3.0) - so that's something to keep an eye on.

For argument's sake - could just provide an overload on Generate that takes in an Assembly object instead of a path. Give the caller the option to figure out how to load it.

**Comment by ejball** [comment]
> Do you plan on publishing your version?

No, it was for a different project entirely, not related to XmlDocMarkdown.

**Comment by sungam3r** [comment]
Relates to #36
